### ISSUE TITLE
Redundant parameters of sf_serialmac_tx_frame()

### ISSUE THREAD

**Issue by jobrud** [stackforce/serial-interface-mac#4]
There are two parameters describing the length of the frame/buffer:
* ` frame_length` Length of the frame to send.
* `frame_buffer_size` Length of the buffer containing the payload to be appended to the frame.

It should be checked if this is meaningful. In case not, one parameter should be removed.

**Comment by mrpelotazo** [comment]
The point of having both length/size parameters is to be able to initialize the frame and assign payload to it in one call i.e. without the need to explicitly call both **sf_serialmac_tx_frame_start** and **sf_serialmac_tx_frame_append** (**sf_serialmac_tx_frame()** does this internally).
* This allows to use just one call if the suplied **frame_buffer** is all one wants to send. In such case both **frame_length** and **frame_buffer_size** parameters would be the same in the **sf_serialmac_tx_frame()** call.
* Otherwise if **frame_length** > **frame_buffer_size** the **tx_buffer_event** callback will be triggered with the number of processed bytes giving the upper layer the chance to append more elements to the payload until the **frame_length** is reached.
* Appending data to the frame over the configured frame size will cause the exceeding data to be ignored as stated in the **sf_serialmac_tx_frame_append()** doc:

> Remaining payload that did not fit into the frame is ignored. The number of
> processed payload bytes is passed to tx_event().

Therefore the parameter is not redundant and this issue is invalid.
